name: Docker Hub

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Build Docker image
      run: |
        docker build -t bot .
        docker tag bot matteocontrini/expelliarbusbot:latest
        docker tag bot matteocontrini/expelliarbusbot:$(git rev-parse --short HEAD)
    
    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" > docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push matteocontrini/expelliarbusbot
